"use strict";

/**
 * Server Trust Boundary HTTP Adapter.
 *
 * This layer performs transport-to-application adaptation only.
 * Business orchestration belongs to
 * ServerTrustBoundaryIngestionService.
 *
 * requestId is generated by the outer transport boundary.
 * Internal error codes are never exposed directly.
 */
class ServerTrustBoundaryHttpAdapter {
    constructor({
        ingestionService,
        diagnosticLogger
    } = {}) {
        if (
            !ingestionService ||
            typeof ingestionService.ingest !== "function"
        ) {
            throw new Error(
                "ServerTrustBoundaryHttpAdapter requires ingestionService"
            );
        }

        this.ingestionService =
            ingestionService;

        this.diagnosticLogger =
            diagnosticLogger &&
            typeof diagnosticLogger.error === "function"
                ? diagnosticLogger
                : null;
    }

    diagnoseError(requestId, internalErrorCode) {
        if (!this.diagnosticLogger) {
            return;
        }

        try {
            this.diagnosticLogger.error({
                requestId,
                status: "error",
                internalErrorCode
            });
        } catch (error) {
            // Diagnostics must never affect request processing.
        }
    }

    toConnectorResponse(result, requestId) {
        if (
            result &&
            (
                result.status === "matched" ||
                result.status === "needs_review" ||
                result.status === "unmatched"
            )
        ) {
            return {
                requestId,
                status: result.status
            };
        }

        if (
            result &&
            result.status === "denied"
        ) {
            return {
                requestId,
                status: "denied",
                errorCode:
                    "connector_trust_denied"
            };
        }

        if (
            result &&
            result.status === "invalid"
        ) {
            return {
                requestId,
                status: "invalid",
                errorCode:
                    "connector_payload_invalid"
            };
        }

        if (
            result &&
            result.status === "error"
        ) {
            this.diagnoseError(
                requestId,
                typeof result.errorCode === "string" &&
                result.errorCode.trim()
                    ? result.errorCode
                    : "connector_processing_error"
            );

            return {
                requestId,
                status: "error",
                errorCode:
                    "connector_processing_unavailable"
            };
        }

        this.diagnoseError(
            requestId,
            "application_result_invalid"
        );

        return {
            requestId,
            status: "error",
            errorCode:
                "internal_result_invalid"
        };
    }

    async handle({
        requestId,
        connectorId,
        credential,
        payload,
        semanticRecords
    } = {}) {
        let result;

        try {
            result =
                await this.ingestionService.ingest({
                    connectorId,
                    credential,
                    payload,
                    semanticRecords
                });
        } catch (error) {
            this.diagnoseError(
                requestId,
                "ingestion_application_exception"
            );

            return {
                requestId,
                status: "error",
                errorCode:
                    "connector_processing_unavailable"
            };
        }

        return this.toConnectorResponse(
            result,
            requestId
        );
    }
}

module.exports =
    ServerTrustBoundaryHttpAdapter;
